apiVersion: v1
kind: Service
metadata:
  name: {{ include "prguard.fullname" . }}-api
  labels:
    {{- include "prguard.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "prguard.name" . }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.api.port }}
